version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
    container_name: nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000

  backend:
    build:
      context: ./apps/backend
    container_name: express-api
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: passwordsavoir
      POSTGRES_DB: espace-savoir
      JWT_SECRET: change_this_in_production

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: passwordsavoir
      POSTGRES_DB: espace-savoir
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres-data:
